FROM node:10.16.0-alpine

EXPOSE 3000
EXPOSE 8080
EXPOSE 9000

# Add core utils
RUN set -x && \
  apk --no-cache upgrade && \
  apk --no-cache add \
    bash \
    curl \
    vim \
    git \
    zsh \
    openssh-client && \
  rm -rf /var/cache/apk/*

# Install Python 2 (for node-gyp)
RUN apk add --no-cache python && \
  python -m ensurepip && \
  rm -r /usr/lib/python*/ensurepip && \
  pip install --upgrade pip setuptools && \
  rm -r /root/.cache

# Copy ssh keys
COPY .ssh /root/.ssh
RUN chmod 400 /root/.ssh/*_id_rsa && \
  chmod 600 /root/.ssh/*.pub && \
  eval $(ssh-agent -s) && \
  ssh-add ~/.ssh/*_id_rsa

# Setup Yarn cache
ENV YARN_CACHE_FOLDER /yarn_cache
RUN mkdir -p $YARN_CACHE_FOLDER
RUN yarn config set cache-folder $YARN_CACHE_FOLDER

# Install oh-my-zsh
RUN curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

# Start zsh
ENV ZSH_THEME agnoster
CMD ["zsh"]