FROM ubuntu:latest
# Set docker default shell to bash login shell
SHELL ["/bin/bash", "--login", "-c"]

# Install base dependencies
RUN apt-get update && apt-get install -y sudo curl zsh wget vim git

# Install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

# Install node
ENV NVM_DIR /root/.nvm
ENV NODE_VERSION 10.16.0
RUN source $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update \
  && apt-get install -y yarn

# Install oh-my-zsh
RUN curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

# Copy ssh keys
COPY .ssh /root/.ssh
RUN chmod 400 /root/.ssh/*_id_rsa \
  && chmod 600 /root/.ssh/*.pub \
  && eval $(ssh-agent -s) \
  && ssh-add ~/.ssh/*_id_rsa

EXPOSE 3000

# Start zsh
ENV ZSH_THEME agnoster
CMD ["zsh"]
