FROM node:10.16.0-alpine

EXPOSE 3000
EXPOSE 8080
EXPOSE 9000

# Add core utils
RUN set -x && \
  apk --no-cache upgrade && \
  apk --no-cache add \
    bash \
    curl \
    vim \
    git \
    zsh \
    openssh-client \
  && rm -rf /var/cache/apk/*

# Copy ssh keys
COPY .ssh /root/.ssh
RUN chmod 400 /root/.ssh/*_id_rsa \
  && chmod 600 /root/.ssh/*.pub \
  && eval $(ssh-agent -s) \
  && ssh-add ~/.ssh/*_id_rsa

# Install oh-my-zsh
RUN curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | bash

# Start zsh
ENV ZSH_THEME agnoster
CMD ["zsh"]